# Copyright 2020 YourBase Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:18.04
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y git build-essential libssl-dev libreadline-dev \
                                                  zlib1g-dev libbz2-dev libsqlite3-dev ca-certificates \
                                                  curl wget libtool-bin tzdata file 

# I'd like to avoid this but for now... ‾\_('')_/‾
RUN DEBIAN_FRONTEND=noninteractive apt install -y software-properties-common libpq-dev libmysqlclient-dev \
                                                  imagemagick libxml2-dev libxslt-dev libtool-bin libyaml-dev \
                                                  libreadline-dev autoconf pkg-config gettext libglib2.0-dev \
                                                  libyaml-0-2 libmagickcore-dev
