FROM ubuntu:16.04
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y git build-essential libssl-dev libreadline-dev zlib1g-dev libbz2-dev \
                                                  libsqlite3-dev ca-certificates wget curl software-properties-common \
                                                  tzdata file 
# I'd like to avoid this but for now... ‾\_('')_/‾
RUN DEBIAN_FRONTEND=noninteractive apt install -y libpq-dev libmysqlclient-dev imagemagick libxml2-dev libxslt-dev \
                                                  libyaml-0-2 libyaml-dev libreadline-dev autoconf pkg-config gettext libtool-bin 

# 16.04 specific?
RUN apt install -y libglib2.0-dev
