# Copyright 2020 YourBase Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:18.04

# Please keep the following list sorted.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    autoconf \
    build-essential \
    bzip2 \
    ca-certificates \
    curl \
    file \
    gettext \
    git \
    gzip \
    imagemagick \
    jq \
    libbz2-dev \
    libglib2.0-dev \
    libmagickcore-dev \
    libmysqlclient-dev \
    libpq-dev \
    libreadline-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libtool-bin \
    libxml2-dev \
    libxslt-dev \
    libyaml-0-2 \
    libyaml-dev \
    openssh-client \
    pkg-config \
    software-properties-common \
    tar \
    tzdata \
    unzip \
    wget \
    xz-utils \
    zip \
    zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*
